# Generated by Django 2.0.13 on 2019-02-23 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
